config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Groups
  post 'groups/:id/adduser', to: 'groups#adduser'
  get  'groups/all',         to: 'groups#all'

  resources :gifts
  resources :groups

  root 'welcome#index'

  # User Auth
  get    'sign_up', to: 'registrations#new'
  post   'sign_up', to: 'registrations#create'
  get    'sign_in', to: 'sessions#new'
  post   'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get    'password', to: 'passwords#edit', as: 'edit_password'
  patch  'password', to: 'passwords#update'
  get    'password/reset', to: 'password_resets#new'
  post   'password/reset', to: 'password_resets#create'
  get    'password/reset/edit', to: 'password_resets#edit'
  patch  'password/reset/edit', to: 'password_resets#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  # makes Current.user accessible in view files.
  attribute :user
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :creator_user, :class_name => 'User', :foreign_key => 'creator_user_id'
  belongs_to :for_user,     :class_name => 'User', :foreign_key => 'for_user_id'
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :gifts
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
  has_and_belongs_to_many :groups
  has_many :created_gifts, :class_name => 'Gift', :foreign_key => 'creator_user_id'
  has_many :for_gifts,     :class_name => 'Gift', :foreign_key => 'for_user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  def set_current_user
    # finds user with session data and stores it if present
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end
  def require_user_logged_in!
    # allows only logged in user
    redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  def new
  end
  def create
    render plain: params[:gift].inspect
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user_logged_in!
  def new
    @group = Group.new
  end
  def create
    @group = Group.new(group_params)
    @group.users << Current.user

    if @group.save
      redirect_to @group
    else
      render :new
    end
  end
 
  def show
    @group = Group.find(params[:id])
    if not @group.users.exists?(Current.user.id)
       flash[:alert] = 'You are not a member of group: ' + @group.name
       redirect_to groups_path
    end
  end

  def index
    @groups = Current.user.groups
  end
  def all
    # Secret all group page
    @groups = Group.all
  end

  def adduser
    @user_params = user_email_params
    @user  = User.find_by_email(@user_params[:email])
    @group = Group.find(params[:id])
    if @user.nil?
      flash[:alert] = 'Invalid email address: ' + @user_params[:email]
    elsif @group.users.exists?(@user.id)
      flash[:alert] = 'Email address already in group: ' + @user_params[:email]
    else
      @group.users << @user
      @group.save
    end
    redirect_to @group
  end
 
  private
  def group_params
    params.require(:group).permit(:name, :description)
  end
  def user_email_params
    params.require(:user).permit(:email)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  def edit
    # finds user with a valid token
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: 'Your token has expired. Please try again.'
  end
  def update
    # updates user's password
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    if @user.update(password_params)
      redirect_to sign_in_path, notice: 'Your password was reset successfully. Please sign in'
    else
      render :edit
    end
  end
  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  # allows only logged in users
  before_action :require_user_logged_in!
  def edit 
  end
  def update
    # update user password
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password Updated'
    else
      render :edit
    end
  end
  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  # instantiates new user
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      # stores saved user id in a session
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Successfully created account'
    else
      render :new
    end
  end
  private
  def user_params
    # strong parameters
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:email])
    # finds existing user, checks to see if user can be authenticated
    if user.present? && user.authenticate(params[:password])
      # sets up user.id sessions
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end
  def destroy
    # deletes user session
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged Out'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gifts/new.html.erb
<h1>New Gift</h1>


<%= form_with scope: :gift, url: gifts_path, local: true do |form| %>
   <p>
      <%= form.label      :name %><br>
      <%= form.text_field :name %>
   </p>
   <p>
      <%= form.label      :description %><br>
      <%= form.text_field :description %>
   </p>
   <p>
      <%= form.submit %>
   </p>
<% end %>

app/views/groups/all.html.erb
<h1>All Groups List</h1>

<ul>
   <% @groups.each do |group| %>
      <li>
         <%= link_to group.name, group %>
      </li>
   <% end %>
</ul>

<%= link_to "New Group", new_group_path %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<ul>
   <% @groups.each do |group| %>
      <li>
         <%= link_to group.name, group %>
      </li>
   <% end %>
</ul>

<%= link_to "New Group", new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>


<%= form_with scope: :group, url: groups_path, local: true do |form| %>
   <p>
      <%= form.label      :name %><br>
      <%= form.text_field :name %>
   </p>
   <p>
      <%= form.label      :description %><br>
      <%= form.text_field :description %>
   </p>
   <p>
      <%= form.submit %>
   </p>
<% end %>

app/views/groups/show.html.erb
<h1>Group: <%= @group.name %></h1>

<p><b>Description:</b></p>

<p><%= @group.description %></p>

<p><b>Members:</b></p>

<ul>
   <% @group.users.each do |user| %>
      <li>
         <%= user.email %>
      </li>
   <% end %>
</ul>

<p><b>Add Members:</b></p>


<%= form_with scope: :user, url: group_path + '/adduser', local: true do |form| %>
   <p>
      <%= form.label      :email %><br>
      <%= form.text_field :email %>
   </p>
   <p>
      <%= form.submit %>
   </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gift Wizard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello Rails</h1>

<% if Current.user %>
   Logged in as: <%= Current.user.email %><br>
   <%= link_to 'Edit Password', edit_password_path %>
   <%= button_to 'Logout', logout_path, method: :delete %>
<% else %>
   <%= link_to 'Sign Up', sign_up_path %>
   or
   <%= link_to 'Login', sign_in_path %>
<% end %>